### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by guimard** [rexxars/registry-auth-token#33]
Hi,

a simple `npm i && npm run test` fails:
```
  26 passing (119ms)
  4 failing

  1) auth-token
       should return undefined if no auth token is given for registry:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(!getAuthToken())                                                                                                                                                                                            

      + expected - actual

      -false
      +true
      
      at /home/xavier/dev/debian/src/pkg-js/packages/node-registry-auth-token/test/auth-token.test.js:34:7                                                                                                           
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)                                                                                                                                                               

  2) auth-token
       bearer token
         recursively finds registries for deep url if option is set:
     Uncaught AssertionError [ERR_ASSERTION]: does not hang
      at /home/xavier/dev/debian/src/pkg-js/packages/node-registry-auth-token/test/auth-token.test.js:219:16
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)

  3) auth-token
       basic token
         should return undefined if password or username are missing:
     Uncaught AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- {
-   token: 'eGd1aW1hcmQ6Q0V6NEtCMVM3RA==',
-   type: 'Basic'
- }
+ undefined
      at /home/xavier/dev/debian/src/pkg-js/packages/node-registry-auth-token/test/auth-token.test.js:275:16
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)

  4) auth-token
       basic token
         recursively finds registries for deep url if option is set:
     Uncaught AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- {
-   token: 'eGd1aW1hcmQ6Q0V6NEtCMVM3RA==',
-   type: 'Basic'
- }
+ undefined
      at /home/xavier/dev/debian/src/pkg-js/packages/node-registry-auth-token/test/auth-token.test.js:469:16
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)



npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! registry-auth-token@4.1.1 test: `mocha`
npm ERR! Exit status 4
```

node: v10.17.0

**Comment by rexxars** [comment]
Not able to reproduce
